/**
 * Gemini AI Integration for Job Categorization
 */

const GEMINI_API_KEY = process.env.NEXT_PUBLIC_GEMINI_API_KEY_CATEGORY
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'

export interface CategoryResponse {
    category: string
    success: boolean
    error?: string
}

/**
 * Categorize a job using Gemini AI
 * @param jobCaption - The job description/caption
 * @returns Category name generated by Gemini
 */
export async function categorizeJobWithAI(jobCaption: string): Promise<CategoryResponse> {
    if (!GEMINI_API_KEY) {
        console.error('Gemini API key not found')
        return { category: 'Other', success: false, error: 'API key missing' }
    }

    if (!jobCaption || jobCaption.trim().length === 0) {
        return { category: 'Other', success: false, error: 'Empty caption' }
    }

    try {
        const prompt = `Analyze this job posting and create a SHORT, descriptive category name (1-3 words max).
The category should be:
- Clear and specific
- Professional
- Easy to understand
- In English
- Capitalize each word (e.g., "Dog Walking", "AC Repair")

Job caption: "${jobCaption}"

Return ONLY the category name, nothing else. No explanations, no punctuation, just the category.`

        const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{
                        text: prompt
                    }]
                }],
                generationConfig: {
                    temperature: 0.3,
                    maxOutputTokens: 20,
                }
            })
        })

        if (!response.ok) {
            const errorText = await response.text()
            console.error('❌ Gemini API Response:', {
                status: response.status,
                statusText: response.statusText,
                body: errorText,
                url: GEMINI_API_URL
            })
            throw new Error(`Gemini API error: ${response.status} - ${errorText}`)
        }

        const data = await response.json()

        // Extract category from Gemini response
        const category = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || 'Other'

        // Clean up the category (remove quotes, extra spaces, etc.)
        const cleanCategory = category.replace(/['"]/g, '').trim()

        console.log('✅ AI Categorization:', { caption: jobCaption.substring(0, 50), category: cleanCategory })

        return { category: cleanCategory, success: true }
    } catch (error: any) {
        console.error('❌ Gemini categorization error:', error)
        return { category: 'Other', success: false, error: error.message }
    }
}

/**
 * Get all unique categories from jobs
 * @param jobs - Array of jobs
 * @returns Array of unique category names
 */
export function getUniqueCategories(jobs: any[]): string[] {
    const categories = jobs
        .map(job => job.category)
        .filter(category => category && category !== '')

    return Array.from(new Set(categories)).sort()
}
