/**
 * Gemini AI Integration for Job Categorization
 */

const GEMINI_API_KEY = process.env.NEXT_PUBLIC_GEMINI_API_KEY_CATEGORY
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent'

export interface CategoryResponse {
    category: string
    success: boolean
    error?: string
}

/**
 * Category normalization map - ensures consistent categorization
 * Maps various AI-generated category names to standardized ones
 */
const CATEGORY_NORMALIZATION: Record<string, string> = {
    // AC/Cooling related
    'ac': 'AC Repair',
    'ac repair': 'AC Repair',
    'ac service': 'AC Repair',
    'air conditioning': 'AC Repair',
    'air conditioner': 'AC Repair',
    'ac installation': 'AC Repair',
    'ac maintenance': 'AC Repair',
    'hvac': 'AC Repair',

    // Plumbing
    'pl': 'Plumbing',
    'plumbing': 'Plumbing',
    'plumber': 'Plumbing',
    'pipe repair': 'Plumbing',
    'water leak': 'Plumbing',
    'waterleakage': 'Plumbing',
    'water leakage': 'Plumbing',
    'leak': 'Plumbing',
    'leakage': 'Plumbing',
    'pipe leak': 'Plumbing',
    'tap repair': 'Plumbing',
    'faucet repair': 'Plumbing',

    // Electrical
    'el': 'Electrical Work',
    'electrical': 'Electrical Work',
    'electrician': 'Electrical Work',
    'wiring': 'Electrical Work',
    'electric repair': 'Electrical Work',

    // Cleaning
    'cleaning': 'Cleaning',
    'house cleaning': 'Cleaning',
    'home cleaning': 'Cleaning',
    'deep cleaning': 'Cleaning',

    // Pet care
    'dog walking': 'Dog Walking',
    'pet care': 'Pet Care',
    'pet sitting': 'Pet Care',

    // Carpentry
    'carpentry': 'Carpentry',
    'carpenter': 'Carpentry',
    'wood work': 'Carpentry',
    'furniture repair': 'Carpentry',

    // Painting
    'painting': 'Painting',
    'house painting': 'Painting',
    'wall painting': 'Painting',
}

/**
 * Normalize category name to ensure consistency
 */
function normalizeCategory(category: string): string {
    // Clean the response (remove quotes, extra spaces, newlines)
    const cleaned = category
        .replace(/['"]/g, '')
        .replace(/\n/g, '')
        .trim()

    // Check normalization map
    const normalized = cleaned.toLowerCase().trim()
    return CATEGORY_NORMALIZATION[normalized] || cleaned
}

/**
 * Categorize a job using Gemini AI with improved accuracy
 * @param jobCaption - The job description/caption
 * @param existingCategories - Optional array of existing categories for consistency
 * @returns Category name generated by Gemini
 */
export async function categorizeJobWithAI(
    jobCaption: string,
    existingCategories?: string[]
): Promise<CategoryResponse> {
    if (!GEMINI_API_KEY) {
        console.error('Gemini API key not found')
        return { category: 'Other', success: false, error: 'API key missing' }
    }

    if (!jobCaption || jobCaption.trim().length === 0) {
        return { category: 'Other', success: false, error: 'Empty caption' }
    }

    try {
        // Build context-aware prompt with existing categories
        let prompt = `You are a job categorization AI. Analyze the job and assign the BEST specific category.

RULES:
1. Prefer EXISTING CATEGORIES below if the job fits
2. ALWAYS create a NEW specific category if job doesn't fit existing ones
3. Use FULL names, NOT abbreviations (e.g., "Plumbing" not "Pl", "AC Repair" not "AC")
4. Use SHORT names (1-3 words, capitalize each word)
5. Similar jobs should get the SAME category (e.g., all water leaks = Plumbing)
6. NEVER return generic categories - be specific

EXAMPLES:
- "water leakage" → Plumbing
- "water tank leakage" → Plumbing (same as water leakage)
- "pipe burst" → Plumbing (same category)
- "fridge not working" → Appliance Repair
- "AC not working" → AC Repair
- "need electrician" → Electrical Work
- "dog walking" → Dog Walking
- "house cleaning" → Cleaning
- "guitar lessons" → Music Lessons
- "yoga classes" → Yoga Classes`

        // Add existing categories from database
        if (existingCategories && existingCategories.length > 0) {
            const uniqueCategories = Array.from(new Set(existingCategories))
                .filter(cat => cat && cat !== 'Other')
                .slice(0, 15)

            if (uniqueCategories.length > 0) {
                prompt += `\n\nEXISTING CATEGORIES (prefer these if job fits):\n${uniqueCategories.join(', ')}`
            }
        }

        prompt += `\n\nJob caption: "${jobCaption}"

CRITICAL: Return the FULL category name (minimum 2 words for compound categories like "AC Repair", "Appliance Repair"). NO abbreviations like "Pl" or "AC".`

        console.log('🤖 Categorizing job:', jobCaption)
        console.log('📊 Existing categories:', existingCategories)
        console.log('📝 Full prompt length:', prompt.length, 'characters')

        const response = await fetch(`${GEMINI_API_URL}?key=${GEMINI_API_KEY}`, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                contents: [{
                    parts: [{
                        text: prompt
                    }]
                }],
                generationConfig: {
                    temperature: 0.3,
                    maxOutputTokens: 150, // Generous limit to handle all cases
                }
            })
        })

        if (!response.ok) {
            const errorText = await response.text()
            console.error('❌ Gemini API Response:', {
                status: response.status,
                statusText: response.statusText,
                body: errorText,
                url: GEMINI_API_URL
            })
            throw new Error(`Gemini API error: ${response.status} - ${errorText}`)
        }

        const data = await response.json()
        console.log('📦 Full API response:', JSON.stringify(data, null, 2))

        // Extract category from response
        const rawCategory = data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || 'Other'

        // Clean up (remove quotes, newlines, extra spaces only)
        const cleanedCategory = rawCategory
            .replace(/['"]/g, '')
            .replace(/\n/g, '')
            .trim()

        console.log('🔍 Raw AI response:', rawCategory)
        console.log('✅ Final category:', cleanedCategory)

        return {
            category: cleanedCategory,
            success: true
        }
    } catch (error: any) {
        console.error('❌ Categorization error:', error)
        return {
            category: 'Other',
            success: false,
            error: error.message
        }
    }
}

/**
 * Get unique categories from existing jobs
 * @param jobs - Array of jobs
 * @returns Array of unique category names
 */
export function getUniqueCategories(jobs: any[]): string[] {
    const categories = new Set<string>()

    jobs.forEach(job => {
        if (job.category) {
            categories.add(job.category)
        }
    })

    return Array.from(categories).sort()
}
